baseURL = "https://example.com"
defaultContentLanguage = "en"
disqusShortname = "yourdiscussshortname"
googleAnalytics = "UA-123456789-1"
languageCode = "en-us"
pygmentsCodefences = true
pygmentsStyle = "pygments"
theme = "cayman-hugo-theme"
title = "Cayman"
[[menu.nav]]
name = "项目一"
url = "/projetc1"
weight = 4
[[menu.nav]]
name = "介绍"
url = "/about/"
weight = 3
[[menu.nav]]
name = "标题"
url = "/tags/"
weight = 2
[params]
blockquote_text_color = "#819198"
body_link_color = "#1e6bb8"
body_text_color = "#606c71"
border_color = "#dce6f0"
code_background_color = "#f3f6fa"
code_text_color = "#567482"
dateFormat = "2006-01-02"
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
header_background_color = "#159957"
header_background_color_secondary = "#155799"
header_heading_color = "#fff"
hr_border_color = "#eff0f1"
katex = true
large_breakpoint = "64em"
medium_breakpoint = "42em"
project_name = "Cayman Hugo Theme"
project_tagline = "A clean, responsive Hugo theme, ported from the original Jekyll Cayman theme"
section_headings_color = "#159957"
table_border_color = "#e9ebec"
[permalinks]
post = "/:filename/"
[taxonomies]
tag = "tags"
